### ISSUE TITLE
Project editor includes absolute path in config's appbase

### ISSUE THREAD

**Issue by elbaloo** [nunit/nunit-project-editor#10]
I've been working with nunit projects manually and today I noticed that by switching configurations, from the GUI runner, mods are done to the project file.

One of the mods introduces the absolute path just before relative one.
That is, it goes from '......\' to 'D:\svnwc......\'

**Comment by CharliePoole** [comment]
This change to the project file was done by the old V2 gui when the project config was changed. So it's really not a project-editor bug, even though the gui made the change using the project editor.

The new project editor under development doesn't do this, so I'm closing the issue.
