### ISSUE TITLE
Releases and distribution

### ISSUE THREAD

**Issue by ChrisMaddock** [nunit/nunit-project-editor#12]
As the project editor is still suitable for NUnit 3, I wanted to do a few small bits and pieces to tidy the project up.

With 2.6.4, the project editor was packaged with the installer. How should it be distributed for NUnit 3 - as a separate install, or packaged with the framework/console runner? Should it perhaps be a separate download on http://nunit.org/index.php?p=download, as I assume the GUI will eventually be?

Asking mainly as a pre-cursor to #9 - and also as build-from-source seems the only current option, perhaps a release on GitHub may be good in the meanwhile?

**Comment by CharliePoole** [comment]
You're right. I thought we would have a standalone release long ago. Now that many people no longer have NUnit V2 installed, it's not practical to tell them to run the project editor from that distribution.

I'll create a standalone release of the same binary to get us started.

**Comment by CharliePoole** [comment]
Once this is done, we should evaluate the changes already made and decide whether an update is called for in the form of an 0.9.1 or 0.91 release.

**Comment by CharliePoole** [comment]
As to the form of the release, I'm thinking of a simple binary zip. Since it's a tool rather than a library, it doesn't make sense to me to have a nuget download. What do you think?

**Comment by rprouse** [comment]
I think a zip is all we need for now. NuGet doesn't seem right to me. We can do an MSI later if people want it.

**Comment by ChrisMaddock** [comment]
Agreed on the zip.

Does Github record the number of downloads? It would be interesting to see how much use it gets - I only ended up here after someone mentioned it on StackOverflow. It doesn't seem to be a project which attracts a lot of attention, but if it's always been bundled with the rest of NUnit, then I guess there's not really much insight in to who's using it without problem.

Did it/will it integrate with the GUI at all?

**Comment by CharliePoole** [comment]
Originally, it was a part of the GUI - a library assembly. At some point in
history, I decided to make it a stand-alone executable, doing it's own
thing. I eventually removed all references to NUnit from it. That is, it
understands the file format but doesn't use NUnit at all.

In both of it's incarnations - as a library and as an exe - it was
integrated with the Gui. Currently, in 2.6.4, it is launched by the menu
and the Gui simply watches for changes in the loaded project file. We will
eventually have to decide if we want to do that for the new GUI, but I
don't think it's urgent to do so.

In fact, I've been telling people to use it standalone for years, but only
in responses to questions on forums or lists. We have never documented it
separately from the GUI itself so I imagine many people think of it as a
part of the GUI.

Regarding an msi... I don't want to create one until we decide whether we
are keeping our other msis. They are certainly a pain to maintain.

**Comment by rprouse** [comment]
@ChrisMaddock GitHub doesn't expose the downloads, but we have been getting them from http://www.somsubhra.com/github-release-stats/

Combining those numbers with the NuGet downloads helps us to concentrate our efforts where they will see the biggest impact rather than be swayed by a few vocal users :smile:

**Comment by ChrisMaddock** [comment]
Great, thanks Rob, and thanks Charlie re: the background. Will be interesting to see if it does get much use as an independent tool.

**Comment by CharliePoole** [comment]
I created release 0.9, a standalone equivalent to the version distributed with NUnit 2.6.4.
