### ISSUE TITLE
Next release

### ISSUE THREAD

**Issue by ChrisMaddock** [nunit/nunit-project-editor#20]
We talked earlier in the year about finishing the current roadmap, and making that release 1.0. I never got back to the remaining issues, but @rprouse finished them off a couple of weeks ago.

The current roadmap is 0.91, but in my opinion, there's nothing here we're actively planning to work on (unless I'm mistaken?), so calling it 1.0 would be sensible. This hasn't really had a proper release since it stopped being distributed as part of NUnit 2x - I think it would be good to do one proper release, and see what's needed after that.

We decided before that a zip distribution was enough - if we just put that here, and on nunit.org, does that seem sensible?

**Comment by immeraufdemhund** [comment]
Sounds good to me.

**Comment by rprouse** [comment]
Sounds good to me too although nunit.org should just link to this repos releases section.

**Comment by CharliePoole** [comment]
@ChrisMaddock I agree. I think we already talked about this and it's what I planned to do.

**Comment by ChrisMaddock** [comment]
@CharliePoole - Sorry - if it's already on your list, I'll leave it with you. 😄  I wasn't sure if anyone was looking at this project at the moment - and didn't want the previous work to just sit unreleased.

**Comment by CharliePoole** [comment]
No sweat... it's still 10 days off!

As a pre-1.0 project, this gets a somewhat looser treatment than our production products. But going to 1.0 is kind of a big deal, even though it's substantially the same as what's in V2, so I'm thinking about an RC.

**Comment by CharliePoole** [comment]
It was a little confusing for me to have an issue "Do 0.9.1 release in the 0.9.1 milestone" 😄 I'll keep this open till the new milestone / release plan is set up.

**Comment by CharliePoole** [comment]
See new milestone 1.0 for resolution.
