### ISSUE TITLE
Add download instructions in readme.md

### ISSUE THREAD

**Issue by IronSean** [nunit/nunit-project-editor#29]
The readme says this is bundled with the GUI, and available as a standalone download. I might just be in need of a coffee, but I can't seem to find downloads for it on the Nunit site or NuGet. 

It might be helpful to add a quick section to the Readme specifying where precompiled versions can be found.

**Comment by ChrisMaddock** [comment]
The download is available on the [releases page](https://github.com/nunit/nunit-project-editor/releases), and on [Chocolatey](https://chocolatey.org/packages/nunit-project-editor). 

I think it's a fair point that that could be included in the readme. 😄

**Comment by CharliePoole** [comment]
Actually, the readme says that it __will__ be bundled with the GUI, but users probably won't read it closely enough to notice that. :-)

I'll try to make it clearer.
