### ISSUE TITLE
CI Server for nunit-project-editor

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit-project-editor#9]
Build and test on each commit.

**Comment by ChrisMaddock** [comment]
@CharliePoole/@rprouse: Would someone mind enabling the web hooks on PRs for this repo, and also enabling Travis builds?

I can force Appveyor to run on my branch, but Travis seems to require elevated permissions to do that.

Thanks!

**Comment by CharliePoole** [comment]
I enabled it to run on both Appveyor and Travis.

**Comment by ChrisMaddock** [comment]
Thanks @CharliePoole - back to work now, but should be able to get it finished off tonight!
